package financeiro;


/**
* financeiro/contaCorrente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from financeiro.idl
* Sexta-feira, 19 de Abril de 2024 20h30min59s BRT
*/

public interface contaCorrente extends contaCorrenteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface contaCorrente
